// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TetaCode.Data;

#nullable disable

namespace TetaCode.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316000917_SeedSampleData")]
    partial class SeedSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TetaCode.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "demo@tetacode.com",
                            FullName = "Demo Kullanıcı",
                            PasswordHash = "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"
                        });
                });

            modelBuilder.Entity("TetaCode.Core.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Genel",
                            CreatedAt = new DateTime(2025, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OOP'nin dört temel prensibi: Encapsulation (kapsülleme), Inheritance (kalıtım), Polymorphism (çok biçimlilik) ve Abstraction (soyutlama). Sınıflar ve nesneler arasındaki ilişkiler, SOLID prensipleri ile sürdürülebilir kod yapısı.",
                            IsDeleted = false,
                            Tags = "OOP,C#,programlama,temel",
                            Title = "Nesne Yönelimli Programlama Temelleri",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Vize",
                            CreatedAt = new DateTime(2025, 3, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1NF, 2NF, 3NF ve BCNF kuralları. Birincil ve yabancı anahtarlar, indeksler, sorgu optimizasyonu. İlişkisel model ve ER diyagramları.",
                            IsDeleted = false,
                            Tags = "SQL,veritabanı,normalizasyon",
                            Title = "Veritabanı Tasarımı ve Normalizasyon",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Final",
                            CreatedAt = new DateTime(2025, 3, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GET, POST, PUT, PATCH, DELETE kullanımı. Status kodları (200, 201, 400, 401, 404, 500). JSON formatı, versioning ve güvenlik (JWT, API Key).",
                            IsDeleted = false,
                            Tags = "API,REST,HTTP,backend",
                            Title = "REST API ve HTTP Metodları",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Genel",
                            CreatedAt = new DateTime(2025, 3, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Domain (Core), Application (Use Cases), Infrastructure (Data, API). Bağımlılık yönü: dış katmanlar içe bağımlı, iç katmanlar dışa bağımlı olmaz. Interface'ler ve Dependency Injection.",
                            IsDeleted = false,
                            Tags = "mimari,.NET,Clean Architecture",
                            Title = "Clean Architecture Katmanları",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Vize",
                            CreatedAt = new DateTime(2025, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Code-First yaklaşımı, DbContext, Fluent API ve Data Annotations. Migration oluşturma (Add-Migration, Update-Database). HasData ile seed verisi ekleme.",
                            IsDeleted = false,
                            Tags = "EF Core,ORM,migration,veritabanı",
                            Title = "Entity Framework Core ve Migration",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TetaCode.Core.Entities.Note", b =>
                {
                    b.HasOne("TetaCode.Core.Entities.AppUser", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TetaCode.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
